FROM node:16.9.0-alpine as build-stage
RUN npm install -g http-server
WORKDIR /app
COPY . .
COPY .env.dev .env
RUN npm install
RUN npm run build
#EXPOSE 8080
#CMD [ "http-server","dist", "-P http://0.0.0.0:8080?" ]
#ENTRYPOINT ["scripts/entrypoint.prod.sh"]

FROM nginx:stable-alpine as production-stage
#VOLUME /var/log/nginx
RUN apk add nano
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html/merchant-backoffice
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
