FROM node:16.9.0-alpine
RUN npm install -g http-server
WORKDIR /app
COPY . .
COPY .env.prod .env
RUN npm install
RUN npm run build
EXPOSE 8080
CMD [ "http-server -P http://0.0.0.0:8080?", "dist" ]
#ENTRYPOINT ["scripts/entrypoint.prod.sh"]
